export {
	isObjectOrArray,
	pickToArray,
	postDFSObjectTraversal,
	flatObj,
	mapFilter,
	mapFind,
	mapGroups,
	mapPartition,
	mapTupleToObject,
	mergeByPattern,
	twoPointerMap,
	twoPointerMapFilter,
	isSuccessfulTreeUpdateStatus,
	mergeSets,
	reduceToObject,
	twoPointerEach,
	replaceByPattern,
	treeBFS,
	product,
	reduceToMultiObject,
	treeUpdateStatus,
	getEntriesOfObjectOrArray,
	getValuesOfObjectOrArray,
	PathError,
	type TreeContext,
	type ObjectTraversalContext,
	type TupleToObject,
	type MapGroupEntries,
	type ObjectOrArray,
} from "./src/index"
